name = "adhyayxp"
main = "src/server.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "adhyayx.site"
custom_domain = true

[[routes]]
pattern = "www.adhyayx.site"
custom_domain = true
