/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PwRouteImport } from './routes/pw'
import { Route as DailyNewsRouteImport } from './routes/daily-news'
import { Route as CurrentAffairsRouteImport } from './routes/current-affairs'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'
import { Route as CategoryStreamRouteImport } from './routes/category.$stream'
import { Route as BooksBookIdRouteImport } from './routes/books_.$bookId'
import { Route as ApiAiRouteImport } from './routes/api.ai'
import { Route as PwTestTestIdRouteImport } from './routes/pw.test.$testId'
import { Route as BooksReadBookIdRouteImport } from './routes/books_.read.$bookId'
import { Route as ApiPublicNewsRouteImport } from './routes/api.public.news'
import { Route as ApiPublicAffairsRouteImport } from './routes/api.public.affairs'
import { Route as ApiPublicPwSplatRouteImport } from './routes/api.public.pw.$'
import { Route as ApiPublicAffairIdRouteImport } from './routes/api.public.affair.$id'
import { Route as ApiBooksDlBookIdRouteImport } from './routes/api.books.dl.$bookId'

const PwRoute = PwRouteImport.update({
  id: '/pw',
  path: '/pw',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyNewsRoute = DailyNewsRouteImport.update({
  id: '/daily-news',
  path: '/daily-news',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAffairsRoute = CurrentAffairsRouteImport.update({
  id: '/current-affairs',
  path: '/current-affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryStreamRoute = CategoryStreamRouteImport.update({
  id: '/category/$stream',
  path: '/category/$stream',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books_/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const PwTestTestIdRoute = PwTestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => PwRoute,
} as any)
const BooksReadBookIdRoute = BooksReadBookIdRouteImport.update({
  id: '/books_/read/$bookId',
  path: '/books/read/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsRoute = ApiPublicNewsRouteImport.update({
  id: '/api/public/news',
  path: '/api/public/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAffairsRoute = ApiPublicAffairsRouteImport.update({
  id: '/api/public/affairs',
  path: '/api/public/affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPwSplatRoute = ApiPublicPwSplatRouteImport.update({
  id: '/api/public/pw/$',
  path: '/api/public/pw/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAffairIdRoute = ApiPublicAffairIdRouteImport.update({
  id: '/api/public/affair/$id',
  path: '/api/public/affair/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksDlBookIdRoute = ApiBooksDlBookIdRouteImport.update({
  id: '/api/books/dl/$bookId',
  path: '/api/books/dl/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/books': typeof BooksRoute
  '/categories': typeof CategoriesRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/daily-news': typeof DailyNewsRoute
  '/pw': typeof PwRouteWithChildren
  '/api/ai': typeof ApiAiRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/category/$stream': typeof CategoryStreamRoute
  '/test/$testId': typeof TestTestIdRoute
  '/api/public/affairs': typeof ApiPublicAffairsRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/books/read/$bookId': typeof BooksReadBookIdRoute
  '/pw/test/$testId': typeof PwTestTestIdRoute
  '/api/books/dl/$bookId': typeof ApiBooksDlBookIdRoute
  '/api/public/affair/$id': typeof ApiPublicAffairIdRoute
  '/api/public/pw/$': typeof ApiPublicPwSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/books': typeof BooksRoute
  '/categories': typeof CategoriesRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/daily-news': typeof DailyNewsRoute
  '/pw': typeof PwRouteWithChildren
  '/api/ai': typeof ApiAiRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/category/$stream': typeof CategoryStreamRoute
  '/test/$testId': typeof TestTestIdRoute
  '/api/public/affairs': typeof ApiPublicAffairsRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/books/read/$bookId': typeof BooksReadBookIdRoute
  '/pw/test/$testId': typeof PwTestTestIdRoute
  '/api/books/dl/$bookId': typeof ApiBooksDlBookIdRoute
  '/api/public/affair/$id': typeof ApiPublicAffairIdRoute
  '/api/public/pw/$': typeof ApiPublicPwSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/books': typeof BooksRoute
  '/categories': typeof CategoriesRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/daily-news': typeof DailyNewsRoute
  '/pw': typeof PwRouteWithChildren
  '/api/ai': typeof ApiAiRoute
  '/books_/$bookId': typeof BooksBookIdRoute
  '/category/$stream': typeof CategoryStreamRoute
  '/test/$testId': typeof TestTestIdRoute
  '/api/public/affairs': typeof ApiPublicAffairsRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/books_/read/$bookId': typeof BooksReadBookIdRoute
  '/pw/test/$testId': typeof PwTestTestIdRoute
  '/api/books/dl/$bookId': typeof ApiBooksDlBookIdRoute
  '/api/public/affair/$id': typeof ApiPublicAffairIdRoute
  '/api/public/pw/$': typeof ApiPublicPwSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/books'
    | '/categories'
    | '/current-affairs'
    | '/daily-news'
    | '/pw'
    | '/api/ai'
    | '/books/$bookId'
    | '/category/$stream'
    | '/test/$testId'
    | '/api/public/affairs'
    | '/api/public/news'
    | '/books/read/$bookId'
    | '/pw/test/$testId'
    | '/api/books/dl/$bookId'
    | '/api/public/affair/$id'
    | '/api/public/pw/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/books'
    | '/categories'
    | '/current-affairs'
    | '/daily-news'
    | '/pw'
    | '/api/ai'
    | '/books/$bookId'
    | '/category/$stream'
    | '/test/$testId'
    | '/api/public/affairs'
    | '/api/public/news'
    | '/books/read/$bookId'
    | '/pw/test/$testId'
    | '/api/books/dl/$bookId'
    | '/api/public/affair/$id'
    | '/api/public/pw/$'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/books'
    | '/categories'
    | '/current-affairs'
    | '/daily-news'
    | '/pw'
    | '/api/ai'
    | '/books_/$bookId'
    | '/category/$stream'
    | '/test/$testId'
    | '/api/public/affairs'
    | '/api/public/news'
    | '/books_/read/$bookId'
    | '/pw/test/$testId'
    | '/api/books/dl/$bookId'
    | '/api/public/affair/$id'
    | '/api/public/pw/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  BooksRoute: typeof BooksRoute
  CategoriesRoute: typeof CategoriesRoute
  CurrentAffairsRoute: typeof CurrentAffairsRoute
  DailyNewsRoute: typeof DailyNewsRoute
  PwRoute: typeof PwRouteWithChildren
  ApiAiRoute: typeof ApiAiRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  CategoryStreamRoute: typeof CategoryStreamRoute
  TestTestIdRoute: typeof TestTestIdRoute
  ApiPublicAffairsRoute: typeof ApiPublicAffairsRoute
  ApiPublicNewsRoute: typeof ApiPublicNewsRoute
  BooksReadBookIdRoute: typeof BooksReadBookIdRoute
  ApiBooksDlBookIdRoute: typeof ApiBooksDlBookIdRoute
  ApiPublicAffairIdRoute: typeof ApiPublicAffairIdRoute
  ApiPublicPwSplatRoute: typeof ApiPublicPwSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pw': {
      id: '/pw'
      path: '/pw'
      fullPath: '/pw'
      preLoaderRoute: typeof PwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-news': {
      id: '/daily-news'
      path: '/daily-news'
      fullPath: '/daily-news'
      preLoaderRoute: typeof DailyNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-affairs': {
      id: '/current-affairs'
      path: '/current-affairs'
      fullPath: '/current-affairs'
      preLoaderRoute: typeof CurrentAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$stream': {
      id: '/category/$stream'
      path: '/category/$stream'
      fullPath: '/category/$stream'
      preLoaderRoute: typeof CategoryStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books_/$bookId': {
      id: '/books_/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pw/test/$testId': {
      id: '/pw/test/$testId'
      path: '/test/$testId'
      fullPath: '/pw/test/$testId'
      preLoaderRoute: typeof PwTestTestIdRouteImport
      parentRoute: typeof PwRoute
    }
    '/books_/read/$bookId': {
      id: '/books_/read/$bookId'
      path: '/books/read/$bookId'
      fullPath: '/books/read/$bookId'
      preLoaderRoute: typeof BooksReadBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news': {
      id: '/api/public/news'
      path: '/api/public/news'
      fullPath: '/api/public/news'
      preLoaderRoute: typeof ApiPublicNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/affairs': {
      id: '/api/public/affairs'
      path: '/api/public/affairs'
      fullPath: '/api/public/affairs'
      preLoaderRoute: typeof ApiPublicAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pw/$': {
      id: '/api/public/pw/$'
      path: '/api/public/pw/$'
      fullPath: '/api/public/pw/$'
      preLoaderRoute: typeof ApiPublicPwSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/affair/$id': {
      id: '/api/public/affair/$id'
      path: '/api/public/affair/$id'
      fullPath: '/api/public/affair/$id'
      preLoaderRoute: typeof ApiPublicAffairIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/dl/$bookId': {
      id: '/api/books/dl/$bookId'
      path: '/api/books/dl/$bookId'
      fullPath: '/api/books/dl/$bookId'
      preLoaderRoute: typeof ApiBooksDlBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PwRouteChildren {
  PwTestTestIdRoute: typeof PwTestTestIdRoute
}

const PwRouteChildren: PwRouteChildren = {
  PwTestTestIdRoute: PwTestTestIdRoute,
}

const PwRouteWithChildren = PwRoute._addFileChildren(PwRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  BooksRoute: BooksRoute,
  CategoriesRoute: CategoriesRoute,
  CurrentAffairsRoute: CurrentAffairsRoute,
  DailyNewsRoute: DailyNewsRoute,
  PwRoute: PwRouteWithChildren,
  ApiAiRoute: ApiAiRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  CategoryStreamRoute: CategoryStreamRoute,
  TestTestIdRoute: TestTestIdRoute,
  ApiPublicAffairsRoute: ApiPublicAffairsRoute,
  ApiPublicNewsRoute: ApiPublicNewsRoute,
  BooksReadBookIdRoute: BooksReadBookIdRoute,
  ApiBooksDlBookIdRoute: ApiBooksDlBookIdRoute,
  ApiPublicAffairIdRoute: ApiPublicAffairIdRoute,
  ApiPublicPwSplatRoute: ApiPublicPwSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
