/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'
import { Route as CategoryStreamRouteImport } from './routes/category.$stream'
import { Route as ApiPublicNewsRouteImport } from './routes/api.public.news'
import { Route as ApiPublicAffairsRouteImport } from './routes/api.public.affairs'
import { Route as ApiPublicAffairIdRouteImport } from './routes/api.public.affair.$id'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryStreamRoute = CategoryStreamRouteImport.update({
  id: '/category/$stream',
  path: '/category/$stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsRoute = ApiPublicNewsRouteImport.update({
  id: '/api/public/news',
  path: '/api/public/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAffairsRoute = ApiPublicAffairsRouteImport.update({
  id: '/api/public/affairs',
  path: '/api/public/affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAffairIdRoute = ApiPublicAffairIdRouteImport.update({
  id: '/api/public/affair/$id',
  path: '/api/public/affair/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/news': typeof NewsRoute
  '/category/$stream': typeof CategoryStreamRoute
  '/test/$testId': typeof TestTestIdRoute
  '/api/public/affairs': typeof ApiPublicAffairsRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/api/public/affair/$id': typeof ApiPublicAffairIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/news': typeof NewsRoute
  '/category/$stream': typeof CategoryStreamRoute
  '/test/$testId': typeof TestTestIdRoute
  '/api/public/affairs': typeof ApiPublicAffairsRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/api/public/affair/$id': typeof ApiPublicAffairIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/news': typeof NewsRoute
  '/category/$stream': typeof CategoryStreamRoute
  '/test/$testId': typeof TestTestIdRoute
  '/api/public/affairs': typeof ApiPublicAffairsRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/api/public/affair/$id': typeof ApiPublicAffairIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/news'
    | '/category/$stream'
    | '/test/$testId'
    | '/api/public/affairs'
    | '/api/public/news'
    | '/api/public/affair/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/news'
    | '/category/$stream'
    | '/test/$testId'
    | '/api/public/affairs'
    | '/api/public/news'
    | '/api/public/affair/$id'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/news'
    | '/category/$stream'
    | '/test/$testId'
    | '/api/public/affairs'
    | '/api/public/news'
    | '/api/public/affair/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  NewsRoute: typeof NewsRoute
  CategoryStreamRoute: typeof CategoryStreamRoute
  TestTestIdRoute: typeof TestTestIdRoute
  ApiPublicAffairsRoute: typeof ApiPublicAffairsRoute
  ApiPublicNewsRoute: typeof ApiPublicNewsRoute
  ApiPublicAffairIdRoute: typeof ApiPublicAffairIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$stream': {
      id: '/category/$stream'
      path: '/category/$stream'
      fullPath: '/category/$stream'
      preLoaderRoute: typeof CategoryStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news': {
      id: '/api/public/news'
      path: '/api/public/news'
      fullPath: '/api/public/news'
      preLoaderRoute: typeof ApiPublicNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/affairs': {
      id: '/api/public/affairs'
      path: '/api/public/affairs'
      fullPath: '/api/public/affairs'
      preLoaderRoute: typeof ApiPublicAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/affair/$id': {
      id: '/api/public/affair/$id'
      path: '/api/public/affair/$id'
      fullPath: '/api/public/affair/$id'
      preLoaderRoute: typeof ApiPublicAffairIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  NewsRoute: NewsRoute,
  CategoryStreamRoute: CategoryStreamRoute,
  TestTestIdRoute: TestTestIdRoute,
  ApiPublicAffairsRoute: ApiPublicAffairsRoute,
  ApiPublicNewsRoute: ApiPublicNewsRoute,
  ApiPublicAffairIdRoute: ApiPublicAffairIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
