/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DailyNewsRouteImport } from './routes/daily-news'
import { Route as CurrentAffairsRouteImport } from './routes/current-affairs'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'
import { Route as CategoryStreamRouteImport } from './routes/category.$stream'
import { Route as ApiPublicNewsRouteImport } from './routes/api.public.news'
import { Route as ApiPublicAffairsRouteImport } from './routes/api.public.affairs'
import { Route as ApiPublicPwSplatRouteImport } from './routes/api.public.pw.$'
import { Route as ApiPublicAffairIdRouteImport } from './routes/api.public.affair.$id'

const DailyNewsRoute = DailyNewsRouteImport.update({
  id: '/daily-news',
  path: '/daily-news',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAffairsRoute = CurrentAffairsRouteImport.update({
  id: '/current-affairs',
  path: '/current-affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryStreamRoute = CategoryStreamRouteImport.update({
  id: '/category/$stream',
  path: '/category/$stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsRoute = ApiPublicNewsRouteImport.update({
  id: '/api/public/news',
  path: '/api/public/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAffairsRoute = ApiPublicAffairsRouteImport.update({
  id: '/api/public/affairs',
  path: '/api/public/affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPwSplatRoute = ApiPublicPwSplatRouteImport.update({
  id: '/api/public/pw/$',
  path: '/api/public/pw/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAffairIdRoute = ApiPublicAffairIdRouteImport.update({
  id: '/api/public/affair/$id',
  path: '/api/public/affair/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/daily-news': typeof DailyNewsRoute
  '/category/$stream': typeof CategoryStreamRoute
  '/test/$testId': typeof TestTestIdRoute
  '/api/public/affairs': typeof ApiPublicAffairsRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/api/public/affair/$id': typeof ApiPublicAffairIdRoute
  '/api/public/pw/$': typeof ApiPublicPwSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/daily-news': typeof DailyNewsRoute
  '/category/$stream': typeof CategoryStreamRoute
  '/test/$testId': typeof TestTestIdRoute
  '/api/public/affairs': typeof ApiPublicAffairsRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/api/public/affair/$id': typeof ApiPublicAffairIdRoute
  '/api/public/pw/$': typeof ApiPublicPwSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/daily-news': typeof DailyNewsRoute
  '/category/$stream': typeof CategoryStreamRoute
  '/test/$testId': typeof TestTestIdRoute
  '/api/public/affairs': typeof ApiPublicAffairsRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/api/public/affair/$id': typeof ApiPublicAffairIdRoute
  '/api/public/pw/$': typeof ApiPublicPwSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/current-affairs'
    | '/daily-news'
    | '/category/$stream'
    | '/test/$testId'
    | '/api/public/affairs'
    | '/api/public/news'
    | '/api/public/affair/$id'
    | '/api/public/pw/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/current-affairs'
    | '/daily-news'
    | '/category/$stream'
    | '/test/$testId'
    | '/api/public/affairs'
    | '/api/public/news'
    | '/api/public/affair/$id'
    | '/api/public/pw/$'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/current-affairs'
    | '/daily-news'
    | '/category/$stream'
    | '/test/$testId'
    | '/api/public/affairs'
    | '/api/public/news'
    | '/api/public/affair/$id'
    | '/api/public/pw/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  CurrentAffairsRoute: typeof CurrentAffairsRoute
  DailyNewsRoute: typeof DailyNewsRoute
  CategoryStreamRoute: typeof CategoryStreamRoute
  TestTestIdRoute: typeof TestTestIdRoute
  ApiPublicAffairsRoute: typeof ApiPublicAffairsRoute
  ApiPublicNewsRoute: typeof ApiPublicNewsRoute
  ApiPublicAffairIdRoute: typeof ApiPublicAffairIdRoute
  ApiPublicPwSplatRoute: typeof ApiPublicPwSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/daily-news': {
      id: '/daily-news'
      path: '/daily-news'
      fullPath: '/daily-news'
      preLoaderRoute: typeof DailyNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-affairs': {
      id: '/current-affairs'
      path: '/current-affairs'
      fullPath: '/current-affairs'
      preLoaderRoute: typeof CurrentAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$stream': {
      id: '/category/$stream'
      path: '/category/$stream'
      fullPath: '/category/$stream'
      preLoaderRoute: typeof CategoryStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news': {
      id: '/api/public/news'
      path: '/api/public/news'
      fullPath: '/api/public/news'
      preLoaderRoute: typeof ApiPublicNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/affairs': {
      id: '/api/public/affairs'
      path: '/api/public/affairs'
      fullPath: '/api/public/affairs'
      preLoaderRoute: typeof ApiPublicAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pw/$': {
      id: '/api/public/pw/$'
      path: '/api/public/pw/$'
      fullPath: '/api/public/pw/$'
      preLoaderRoute: typeof ApiPublicPwSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/affair/$id': {
      id: '/api/public/affair/$id'
      path: '/api/public/affair/$id'
      fullPath: '/api/public/affair/$id'
      preLoaderRoute: typeof ApiPublicAffairIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  CurrentAffairsRoute: CurrentAffairsRoute,
  DailyNewsRoute: DailyNewsRoute,
  CategoryStreamRoute: CategoryStreamRoute,
  TestTestIdRoute: TestTestIdRoute,
  ApiPublicAffairsRoute: ApiPublicAffairsRoute,
  ApiPublicNewsRoute: ApiPublicNewsRoute,
  ApiPublicAffairIdRoute: ApiPublicAffairIdRoute,
  ApiPublicPwSplatRoute: ApiPublicPwSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
